// Default note templates assigned to every new user
// Note: _id will be auto-generated by MongoDB
export const DEFAULT_NOTE_TEMPLATES = [
  {
    name: "الملاحظة اليومية",
    template:
      "# الملاحظة اليومية - {{date}}\n\n## المهام\n- [ ] \n1. \n## ملاحظات\n\n\n## المزاج\n\n\n## الإنجازات\n\n",
  },
  {
    name: "المراجعة الأسبوعية",
    template:
      "# المراجعة الأسبوعية - {{weekStart}} إلى {{weekEnd}}\n\n## الإنجازات\n\n\n## التحديات\n\n\n## أهداف الأسبوع القادم\n\n",
  },
  {
    name: "المراجعة الشهرية",
    template:
      "# المراجعة الشهرية - {{month}} {{year}}\n\n## نظرة عامة\n\n\n## النجاحات\n\n\n## مجالات التحسين\n\n\n## أهداف الشهر القادم\n\n",
  },
];
